import type { DemoUser, Product, Store } from "@/lib/types";

// Example content so the app can be tried before the database is connected.
// Phone numbers are deliberately fake (+53 5 000 0xxx) so no real person gets
// messaged from a demo WhatsApp button.

export const DEMO_STORES: Store[] = [
  {
    id: "s1",
    slug: "mercado-el-sol",
    name: "Mercado El Sol",
    category: "alimentos",
    tagline: "Alimentos y bebidas",
    description: "Productos frescos, de calidad y al mejor precio. Frutas, verduras, lácteos y más para tu mesa.",
    provinceId: "la-habana",
    municipalityId: "plaza-de-la-revolucion",
    address: "Calle 23 entre F y G, Vedado",
    whatsapp: "+53 5 000 0101",
    hours: "Lun – Sáb · 8:00 AM – 8:00 PM",
    openNow: true,
    payment: ["cash", "transfer"],
    delivery: ["pickup", "delivery"],
    deliveryNote: "Domicilio en Plaza y Centro Habana · 200 CUP",
    verified: true,
    featured: true,
    isNew: false,
    productCount: 126,
    distanceKm: 0.9,
    logo: { kind: "icon", value: "Sun", background: "#FFF1C7", foreground: "#E8890C" },
  },
  {
    id: "s2",
    slug: "tecnoyagua",
    name: "TecnoYagua",
    category: "tecnologia",
    tagline: "Electrónica y tecnología",
    description: "Teléfonos, accesorios, cargadores y reparación. Garantía en todos los equipos.",
    provinceId: "la-habana",
    municipalityId: "centro-habana",
    address: "Calle San Rafael, Centro Habana",
    whatsapp: "+53 5 000 0102",
    hours: "Lun – Sáb · 9:00 AM – 6:00 PM",
    openNow: true,
    payment: ["cash", "transfer"],
    delivery: ["pickup", "delivery"],
    deliveryNote: "Domicilio en toda La Habana · consultar costo",
    verified: true,
    featured: true,
    isNew: false,
    productCount: 348,
    distanceKm: 1.2,
    logo: { kind: "initials", value: "TY", background: "#1565C0", foreground: "#FFFFFF" },
  },
  {
    id: "s3",
    slug: "la-esquina",
    name: "La Esquina",
    category: "alimentos",
    tagline: "Variedades",
    description: "De todo un poco para la casa: alimentos, aseo y bebidas.",
    provinceId: "la-habana",
    municipalityId: "plaza-de-la-revolucion",
    address: "Calle 12 y 19, Vedado",
    whatsapp: "+53 5 000 0103",
    hours: "Todos los días · 8:00 AM – 9:00 PM",
    openNow: true,
    payment: ["cash"],
    delivery: ["pickup", "delivery"],
    verified: true,
    featured: true,
    isNew: false,
    productCount: 210,
    distanceKm: 1.5,
    logo: { kind: "icon", value: "Store", background: "#7B3F1D", foreground: "#FFFFFF" },
  },
  {
    id: "s4",
    slug: "todohogar",
    name: "TodoHogar",
    category: "hogar",
    tagline: "Hogar y decoración",
    description: "Electrodomésticos, ollas, ventiladores y artículos para el hogar.",
    provinceId: "la-habana",
    municipalityId: "playa",
    address: "Avenida 41, Playa",
    whatsapp: "+53 5 000 0104",
    hours: "Lun – Vie · 9:00 AM – 5:00 PM",
    openNow: false,
    payment: ["cash", "transfer"],
    delivery: ["pickup", "delivery"],
    verified: true,
    featured: true,
    isNew: false,
    productCount: 412,
    distanceKm: 2.1,
    logo: { kind: "icon", value: "House", background: "#2E8B8B", foreground: "#FFFFFF" },
  },
  {
    id: "s5",
    slug: "bella-moda",
    name: "Bella Moda",
    category: "ropa",
    tagline: "Ropa y accesorios",
    description: "Ropa de mujer, bolsos y accesorios.",
    provinceId: "la-habana",
    municipalityId: "diez-de-octubre",
    address: "Calzada de 10 de Octubre",
    whatsapp: "+53 5 000 0105",
    hours: "Lun – Sáb · 10:00 AM – 6:00 PM",
    openNow: true,
    payment: ["cash", "transfer"],
    delivery: ["pickup"],
    verified: true,
    featured: false,
    isNew: true,
    productCount: 54,
    distanceKm: 3.4,
    logo: { kind: "icon", value: "Flower2", background: "#FBD3DD", foreground: "#C2255C" },
  },
  {
    id: "s6",
    slug: "verde-vida",
    name: "Verde Vida",
    category: "salud",
    tagline: "Salud y bienestar",
    description: "Productos naturales, aseo personal y cuidado de la piel.",
    provinceId: "la-habana",
    municipalityId: "playa",
    address: "Calle 70, Playa",
    whatsapp: "+53 5 000 0106",
    hours: "Lun – Sáb · 9:00 AM – 7:00 PM",
    openNow: true,
    payment: ["cash", "transfer"],
    delivery: ["pickup", "delivery"],
    verified: true,
    featured: false,
    isNew: true,
    productCount: 89,
    distanceKm: 2.8,
    logo: { kind: "icon", value: "Leaf", background: "#DDF3E4", foreground: "#1E843A" },
  },
];

const minutesAgo = (m: number) => new Date(Date.now() - m * 60_000);

/** Built per call so "confirmado hace…" stays relative to the current time. */
export function demoProducts(): Product[] {
  const base = {
    provinceId: "la-habana",
    sponsored: false,
    condition: "new" as const,
    saleMode: "unit" as const,
    tiers: [],
    unitLabel: "unidad",
    availability: "available" as const,
  };
  return [
    {
      ...base,
      id: "p1",
      title: "Aceite vegetal 1 L",
      description: "Aceite vegetal de 1 litro. Ideal para cocinar todos los días.",
      category: "alimentos",
      price: 650,
      currency: "CUP",
      saleMode: "unit_and_bulk",
      tiers: [
        { minQty: 6, unitPrice: 620 },
        { minQty: 12, unitPrice: 590 },
      ],
      confirmedAt: minutesAgo(45),
      createdAt: minutesAgo(60 * 30),
      seller: { type: "store", storeId: "s1" },
      municipalityId: "plaza-de-la-revolucion",
      payment: ["cash", "transfer"],
      delivery: ["pickup", "delivery"],
      sponsored: true,
      distanceKm: 0.9,
    },
    {
      ...base,
      id: "p2",
      title: "Arroz 1 kg",
      description: "Arroz blanco de grano largo, paquete de 1 kg.",
      category: "alimentos",
      price: 380,
      currency: "CUP",
      saleMode: "unit_and_bulk",
      tiers: [{ minQty: 10, unitPrice: 350 }],
      confirmedAt: minutesAgo(90),
      createdAt: minutesAgo(60 * 50),
      seller: { type: "store", storeId: "s1" },
      municipalityId: "plaza-de-la-revolucion",
      payment: ["cash", "transfer"],
      delivery: ["pickup", "delivery"],
      distanceKm: 0.9,
    },
    {
      ...base,
      id: "p3",
      title: "Café molido 250 g",
      description: "Café cubano molido, paquete sellado de 250 g.",
      category: "alimentos",
      price: 900,
      currency: "CUP",
      availability: "low_stock",
      confirmedAt: minutesAgo(20),
      createdAt: minutesAgo(60 * 5),
      seller: { type: "store", storeId: "s3" },
      municipalityId: "plaza-de-la-revolucion",
      payment: ["cash"],
      delivery: ["pickup", "delivery"],
      distanceKm: 1.5,
    },
    {
      ...base,
      id: "p4",
      title: "Audífonos Bluetooth",
      description: "Audífonos inalámbricos con estuche de carga. Batería de hasta 20 horas.",
      category: "tecnologia",
      price: 18,
      currency: "USD",
      confirmedAt: minutesAgo(120),
      createdAt: minutesAgo(60 * 20),
      seller: { type: "store", storeId: "s2" },
      municipalityId: "centro-habana",
      payment: ["cash", "transfer"],
      delivery: ["pickup", "delivery"],
      sponsored: true,
      distanceKm: 1.2,
    },
    {
      ...base,
      id: "p5",
      title: "Cargador USB-C 20 W",
      description: "Cargador rápido con cable USB-C de 1 metro.",
      category: "tecnologia",
      price: 6500,
      currency: "CUP",
      saleMode: "unit_and_bulk",
      tiers: [{ minQty: 5, unitPrice: 6000 }],
      confirmedAt: minutesAgo(200),
      createdAt: minutesAgo(60 * 70),
      seller: { type: "store", storeId: "s2" },
      municipalityId: "centro-habana",
      payment: ["cash", "transfer"],
      delivery: ["pickup", "delivery"],
      distanceKm: 1.2,
    },
    {
      ...base,
      id: "p6",
      title: "Olla de presión 6 L",
      description: "Olla de presión de acero inoxidable, 6 litros.",
      category: "hogar",
      price: 12000,
      offerPrice: 10500,
      currency: "CUP",
      confirmedAt: minutesAgo(60 * 6),
      createdAt: minutesAgo(60 * 26),
      seller: { type: "store", storeId: "s4" },
      municipalityId: "playa",
      payment: ["cash", "transfer"],
      delivery: ["pickup", "delivery"],
      distanceKm: 2.1,
    },
    {
      ...base,
      id: "p7",
      title: "Bicicleta de paseo",
      description: "Bicicleta rodado 26 en buen estado. Frenos y gomas nuevos.",
      category: "vehiculos",
      condition: "used",
      price: 180,
      currency: "USD",
      confirmedAt: minutesAgo(60 * 3),
      createdAt: minutesAgo(60 * 4),
      seller: { type: "person", name: "Carlos M.", whatsapp: "+53 5 000 0201", memberSince: "2026", rating: 4.6 },
      municipalityId: "playa",
      payment: ["cash"],
      delivery: ["pickup"],
      distanceKm: 2.4,
    },
    {
      ...base,
      id: "p8",
      title: "Blusa de algodón",
      description: "Blusa de algodón, tallas S, M y L. Varios colores.",
      category: "ropa",
      price: 2500,
      currency: "CUP",
      confirmedAt: minutesAgo(60 * 8),
      createdAt: minutesAgo(60 * 9),
      seller: { type: "store", storeId: "s5" },
      municipalityId: "diez-de-octubre",
      payment: ["cash", "transfer"],
      delivery: ["pickup"],
      distanceKm: 3.4,
    },
    {
      ...base,
      id: "p9",
      title: "Jabón de baño (pack de 3)",
      description: "Jabón de glicerina, pack de 3 unidades.",
      category: "salud",
      price: 450,
      currency: "CUP",
      saleMode: "unit_and_bulk",
      tiers: [{ minQty: 12, unitPrice: 400 }],
      unitLabel: "pack",
      confirmedAt: minutesAgo(60 * 2),
      createdAt: minutesAgo(60 * 2),
      seller: { type: "store", storeId: "s6" },
      municipalityId: "playa",
      payment: ["cash", "transfer"],
      delivery: ["pickup", "delivery"],
      distanceKm: 2.8,
    },
    {
      ...base,
      id: "p10",
      title: "Samsung Galaxy A15 128 GB",
      description: "Teléfono usado en perfecto estado, con cargador. Batería al 90 %.",
      category: "tecnologia",
      condition: "used",
      price: 120,
      currency: "USD",
      confirmedAt: minutesAgo(30),
      createdAt: minutesAgo(60 * 1),
      seller: { type: "person", name: "Yanet R.", whatsapp: "+53 5 000 0202", memberSince: "2026", rating: 4.9 },
      municipalityId: "centro-habana",
      payment: ["cash", "transfer"],
      delivery: ["pickup"],
      distanceKm: 1.1,
    },
    {
      ...base,
      id: "p11",
      title: "Cemento P-350 (saco 42,5 kg)",
      description: "Cemento gris P-350. Venta mínima 10 sacos. Transporte a coordinar.",
      category: "construccion",
      price: 3200,
      currency: "CUP",
      saleMode: "bulk_only",
      minQty: 10,
      unitLabel: "saco",
      confirmedAt: minutesAgo(60 * 20),
      createdAt: minutesAgo(60 * 48),
      seller: { type: "person", name: "Rafael G.", whatsapp: "+53 5 000 0203", memberSince: "2026", rating: 4.7 },
      municipalityId: "boyeros",
      payment: ["cash", "transfer"],
      delivery: ["pickup", "delivery"],
      deliveryNote: "Entrega en Boyeros y Arroyo Naranjo",
      distanceKm: 6.3,
    },
  ];
}

export const DEMO_USER: DemoUser = {
  name: "Eduardo Pérez",
  initials: "EP",
  rating: 4.8,
  verified: true,
  provinceId: "la-habana",
  plan: { name: "Plan Gratis", activeListings: 7, limit: 10 },
  storeIds: ["s1", "s2"],
};
