-- NODO · reference data: Cuban provinces and municipalities (2011 division:
-- 15 provinces + Isla de la Juventud, 168 municipalities) and product categories.
-- Generated from src/lib/geo/cuba.ts and src/lib/catalog.ts; a unit test keeps them in sync.

insert into public.provinces (id, name, position) values
  ('pinar-del-rio', 'Pinar del Río', 1),
  ('artemisa', 'Artemisa', 2),
  ('la-habana', 'La Habana', 3),
  ('mayabeque', 'Mayabeque', 4),
  ('matanzas', 'Matanzas', 5),
  ('cienfuegos', 'Cienfuegos', 6),
  ('villa-clara', 'Villa Clara', 7),
  ('sancti-spiritus', 'Sancti Spíritus', 8),
  ('ciego-de-avila', 'Ciego de Ávila', 9),
  ('camaguey', 'Camagüey', 10),
  ('las-tunas', 'Las Tunas', 11),
  ('holguin', 'Holguín', 12),
  ('granma', 'Granma', 13),
  ('santiago-de-cuba', 'Santiago de Cuba', 14),
  ('guantanamo', 'Guantánamo', 15),
  ('isla-de-la-juventud', 'Isla de la Juventud', 16);

insert into public.municipalities (province_id, id, name) values
  ('pinar-del-rio', 'consolacion-del-sur', 'Consolación del Sur'),
  ('pinar-del-rio', 'guane', 'Guane'),
  ('pinar-del-rio', 'la-palma', 'La Palma'),
  ('pinar-del-rio', 'los-palacios', 'Los Palacios'),
  ('pinar-del-rio', 'mantua', 'Mantua'),
  ('pinar-del-rio', 'minas-de-matahambre', 'Minas de Matahambre'),
  ('pinar-del-rio', 'pinar-del-rio', 'Pinar del Río'),
  ('pinar-del-rio', 'san-juan-y-martinez', 'San Juan y Martínez'),
  ('pinar-del-rio', 'san-luis', 'San Luis'),
  ('pinar-del-rio', 'sandino', 'Sandino'),
  ('pinar-del-rio', 'vinales', 'Viñales'),
  ('artemisa', 'alquizar', 'Alquízar'),
  ('artemisa', 'artemisa', 'Artemisa'),
  ('artemisa', 'bahia-honda', 'Bahía Honda'),
  ('artemisa', 'bauta', 'Bauta'),
  ('artemisa', 'caimito', 'Caimito'),
  ('artemisa', 'candelaria', 'Candelaria'),
  ('artemisa', 'guanajay', 'Guanajay'),
  ('artemisa', 'guira-de-melena', 'Güira de Melena'),
  ('artemisa', 'mariel', 'Mariel'),
  ('artemisa', 'san-antonio-de-los-banos', 'San Antonio de los Baños'),
  ('artemisa', 'san-cristobal', 'San Cristóbal'),
  ('la-habana', 'arroyo-naranjo', 'Arroyo Naranjo'),
  ('la-habana', 'boyeros', 'Boyeros'),
  ('la-habana', 'centro-habana', 'Centro Habana'),
  ('la-habana', 'cerro', 'Cerro'),
  ('la-habana', 'cotorro', 'Cotorro'),
  ('la-habana', 'diez-de-octubre', 'Diez de Octubre'),
  ('la-habana', 'guanabacoa', 'Guanabacoa'),
  ('la-habana', 'la-habana-del-este', 'La Habana del Este'),
  ('la-habana', 'la-habana-vieja', 'La Habana Vieja'),
  ('la-habana', 'la-lisa', 'La Lisa'),
  ('la-habana', 'marianao', 'Marianao'),
  ('la-habana', 'playa', 'Playa'),
  ('la-habana', 'plaza-de-la-revolucion', 'Plaza de la Revolución'),
  ('la-habana', 'regla', 'Regla'),
  ('la-habana', 'san-miguel-del-padron', 'San Miguel del Padrón'),
  ('mayabeque', 'batabano', 'Batabanó'),
  ('mayabeque', 'bejucal', 'Bejucal'),
  ('mayabeque', 'guines', 'Güines'),
  ('mayabeque', 'jaruco', 'Jaruco'),
  ('mayabeque', 'madruga', 'Madruga'),
  ('mayabeque', 'melena-del-sur', 'Melena del Sur'),
  ('mayabeque', 'nueva-paz', 'Nueva Paz'),
  ('mayabeque', 'quivican', 'Quivicán'),
  ('mayabeque', 'san-jose-de-las-lajas', 'San José de las Lajas'),
  ('mayabeque', 'san-nicolas', 'San Nicolás'),
  ('mayabeque', 'santa-cruz-del-norte', 'Santa Cruz del Norte'),
  ('matanzas', 'calimete', 'Calimete'),
  ('matanzas', 'cardenas', 'Cárdenas'),
  ('matanzas', 'cienaga-de-zapata', 'Ciénaga de Zapata'),
  ('matanzas', 'colon', 'Colón'),
  ('matanzas', 'jaguey-grande', 'Jagüey Grande'),
  ('matanzas', 'jovellanos', 'Jovellanos'),
  ('matanzas', 'limonar', 'Limonar'),
  ('matanzas', 'los-arabos', 'Los Arabos'),
  ('matanzas', 'marti', 'Martí'),
  ('matanzas', 'matanzas', 'Matanzas'),
  ('matanzas', 'pedro-betancourt', 'Pedro Betancourt'),
  ('matanzas', 'perico', 'Perico'),
  ('matanzas', 'union-de-reyes', 'Unión de Reyes'),
  ('cienfuegos', 'abreus', 'Abreus'),
  ('cienfuegos', 'aguada-de-pasajeros', 'Aguada de Pasajeros'),
  ('cienfuegos', 'cienfuegos', 'Cienfuegos'),
  ('cienfuegos', 'cruces', 'Cruces'),
  ('cienfuegos', 'cumanayagua', 'Cumanayagua'),
  ('cienfuegos', 'lajas', 'Lajas'),
  ('cienfuegos', 'palmira', 'Palmira'),
  ('cienfuegos', 'rodas', 'Rodas'),
  ('villa-clara', 'caibarien', 'Caibarién'),
  ('villa-clara', 'camajuani', 'Camajuaní'),
  ('villa-clara', 'cifuentes', 'Cifuentes'),
  ('villa-clara', 'corralillo', 'Corralillo'),
  ('villa-clara', 'encrucijada', 'Encrucijada'),
  ('villa-clara', 'manicaragua', 'Manicaragua'),
  ('villa-clara', 'placetas', 'Placetas'),
  ('villa-clara', 'quemado-de-guines', 'Quemado de Güines'),
  ('villa-clara', 'ranchuelo', 'Ranchuelo'),
  ('villa-clara', 'remedios', 'Remedios'),
  ('villa-clara', 'sagua-la-grande', 'Sagua la Grande'),
  ('villa-clara', 'santa-clara', 'Santa Clara'),
  ('villa-clara', 'santo-domingo', 'Santo Domingo'),
  ('sancti-spiritus', 'cabaiguan', 'Cabaiguán'),
  ('sancti-spiritus', 'fomento', 'Fomento'),
  ('sancti-spiritus', 'jatibonico', 'Jatibonico'),
  ('sancti-spiritus', 'la-sierpe', 'La Sierpe'),
  ('sancti-spiritus', 'sancti-spiritus', 'Sancti Spíritus'),
  ('sancti-spiritus', 'taguasco', 'Taguasco'),
  ('sancti-spiritus', 'trinidad', 'Trinidad'),
  ('sancti-spiritus', 'yaguajay', 'Yaguajay'),
  ('ciego-de-avila', 'baragua', 'Baraguá'),
  ('ciego-de-avila', 'bolivia', 'Bolivia'),
  ('ciego-de-avila', 'chambas', 'Chambas'),
  ('ciego-de-avila', 'ciego-de-avila', 'Ciego de Ávila'),
  ('ciego-de-avila', 'ciro-redondo', 'Ciro Redondo'),
  ('ciego-de-avila', 'florencia', 'Florencia'),
  ('ciego-de-avila', 'majagua', 'Majagua'),
  ('ciego-de-avila', 'moron', 'Morón'),
  ('ciego-de-avila', 'primero-de-enero', 'Primero de Enero'),
  ('ciego-de-avila', 'venezuela', 'Venezuela'),
  ('camaguey', 'camaguey', 'Camagüey'),
  ('camaguey', 'carlos-manuel-de-cespedes', 'Carlos Manuel de Céspedes'),
  ('camaguey', 'esmeralda', 'Esmeralda'),
  ('camaguey', 'florida', 'Florida'),
  ('camaguey', 'guaimaro', 'Guáimaro'),
  ('camaguey', 'jimaguayu', 'Jimaguayú'),
  ('camaguey', 'minas', 'Minas'),
  ('camaguey', 'najasa', 'Najasa'),
  ('camaguey', 'nuevitas', 'Nuevitas'),
  ('camaguey', 'santa-cruz-del-sur', 'Santa Cruz del Sur'),
  ('camaguey', 'sibanicu', 'Sibanicú'),
  ('camaguey', 'sierra-de-cubitas', 'Sierra de Cubitas'),
  ('camaguey', 'vertientes', 'Vertientes'),
  ('las-tunas', 'amancio', 'Amancio'),
  ('las-tunas', 'colombia', 'Colombia'),
  ('las-tunas', 'jesus-menendez', 'Jesús Menéndez'),
  ('las-tunas', 'jobabo', 'Jobabo'),
  ('las-tunas', 'las-tunas', 'Las Tunas'),
  ('las-tunas', 'majibacoa', 'Majibacoa'),
  ('las-tunas', 'manati', 'Manatí'),
  ('las-tunas', 'puerto-padre', 'Puerto Padre'),
  ('holguin', 'antilla', 'Antilla'),
  ('holguin', 'baguanos', 'Báguanos'),
  ('holguin', 'banes', 'Banes'),
  ('holguin', 'cacocum', 'Cacocum'),
  ('holguin', 'calixto-garcia', 'Calixto García'),
  ('holguin', 'cueto', 'Cueto'),
  ('holguin', 'frank-pais', 'Frank País'),
  ('holguin', 'gibara', 'Gibara'),
  ('holguin', 'holguin', 'Holguín'),
  ('holguin', 'mayari', 'Mayarí'),
  ('holguin', 'moa', 'Moa'),
  ('holguin', 'rafael-freyre', 'Rafael Freyre'),
  ('holguin', 'sagua-de-tanamo', 'Sagua de Tánamo'),
  ('holguin', 'urbano-noris', 'Urbano Noris'),
  ('granma', 'bartolome-maso', 'Bartolomé Masó'),
  ('granma', 'bayamo', 'Bayamo'),
  ('granma', 'buey-arriba', 'Buey Arriba'),
  ('granma', 'campechuela', 'Campechuela'),
  ('granma', 'cauto-cristo', 'Cauto Cristo'),
  ('granma', 'guisa', 'Guisa'),
  ('granma', 'jiguani', 'Jiguaní'),
  ('granma', 'manzanillo', 'Manzanillo'),
  ('granma', 'media-luna', 'Media Luna'),
  ('granma', 'niquero', 'Niquero'),
  ('granma', 'pilon', 'Pilón'),
  ('granma', 'rio-cauto', 'Río Cauto'),
  ('granma', 'yara', 'Yara'),
  ('santiago-de-cuba', 'contramaestre', 'Contramaestre'),
  ('santiago-de-cuba', 'guama', 'Guamá'),
  ('santiago-de-cuba', 'mella', 'Mella'),
  ('santiago-de-cuba', 'palma-soriano', 'Palma Soriano'),
  ('santiago-de-cuba', 'san-luis', 'San Luis'),
  ('santiago-de-cuba', 'santiago-de-cuba', 'Santiago de Cuba'),
  ('santiago-de-cuba', 'segundo-frente', 'Segundo Frente'),
  ('santiago-de-cuba', 'songo-la-maya', 'Songo-La Maya'),
  ('santiago-de-cuba', 'tercer-frente', 'Tercer Frente'),
  ('guantanamo', 'baracoa', 'Baracoa'),
  ('guantanamo', 'caimanera', 'Caimanera'),
  ('guantanamo', 'el-salvador', 'El Salvador'),
  ('guantanamo', 'guantanamo', 'Guantánamo'),
  ('guantanamo', 'imias', 'Imías'),
  ('guantanamo', 'maisi', 'Maisí'),
  ('guantanamo', 'manuel-tames', 'Manuel Tames'),
  ('guantanamo', 'niceto-perez', 'Niceto Pérez'),
  ('guantanamo', 'san-antonio-del-sur', 'San Antonio del Sur'),
  ('guantanamo', 'yateras', 'Yateras'),
  ('isla-de-la-juventud', 'isla-de-la-juventud', 'Isla de la Juventud');

insert into public.categories (id, label, position) values
  ('alimentos', 'Alimentos', 1),
  ('tecnologia', 'Tecnología', 2),
  ('hogar', 'Hogar', 3),
  ('ropa', 'Ropa', 4),
  ('salud', 'Salud y belleza', 5),
  ('vehiculos', 'Vehículos', 6),
  ('construccion', 'Construcción', 7),
  ('otros', 'Otros', 8);
